In [61]:
#create a 5d array and find indexing
import numpy as np 
a = np.array ([[[[[5,7,8,8],[2,5,4,5],[1,4,5,6],[1,7,8,9]]]],[[[[9,5,6,4],[2,3,5,6],[1,2,3,4],[5,6,8,9]]]],[[[[5,7,8,8],[2,5,4,5],[1,4,5,6],[1,7,8,9]]]],[[[[9,5,6,4],[2,3,5,6],[1,2,3,4],[2,9,7,8]]]],[[[[9,5,6,4],[2,3,5,6],[1,2,3,4],[2,9,7,8]]]]])
print(a)


[[[[[5 7 8 8]
    [2 5 4 5]
    [1 4 5 6]
    [1 7 8 9]]]]



 [[[[9 5 6 4]
    [2 3 5 6]
    [1 2 3 4]
    [5 6 8 9]]]]



 [[[[5 7 8 8]
    [2 5 4 5]
    [1 4 5 6]
    [1 7 8 9]]]]



 [[[[9 5 6 4]
    [2 3 5 6]
    [1 2 3 4]
    [2 9 7 8]]]]



 [[[[9 5 6 4]
    [2 3 5 6]
    [1 2 3 4]
    [2 9 7 8]]]]]


In [57]:
import numpy as np 
a = np.array ([[1,2,3],[9,4,6],[8,9,5]])
print (a)


[[1 2 3]
 [9 4 6]
 [8 9 5]]


In [19]:
a.shape

(3, 3)

In [21]:
a.strides

(24, 8)

In [23]:
a.ndim

2

In [25]:
a.data

In [27]:
a.size

9

In [29]:
a.itemsize

8

In [47]:
a.base

In [49]:
a.nbytes

72

In [51]:
a.T

array([[1, 9, 8],
       [2, 4, 9],
       [3, 6, 5]])

In [53]:
a.real

array([[1, 2, 3],
       [9, 4, 6],
       [8, 9, 5]])

In [55]:
a.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])